In [1]:
import pandas as pd

df=pd.read_csv(r"C:\Users\Hp\Downloads\Ecommerce_Delivery_Operations_Intelligence_Dataset.csv")
df

,Order_ID,Order_Date,Customer_ID,Customer_Segment,City,Region,Product_Category,Product,Quantity,Unit_Price,Sales_Channel,Delivery_Partner,Order_Value,Expected_Delivery_Date,Actual_Delivery_Date,Order_Status,Delay_Days,Cancellation_Reason,Return_Reason
0,ORD00001,2025-04-13 00:00:00,CUST0196,Corporate,Mumbai,West,Grocery,Coffee,4.0,824.14,Mobile App,Delhivery,3296.56,2025-04-18 00:00:00,2025-04-19 00:00:00,Returned,NaN,NaN,Damaged product
1,ORD00002,2026-03-12 00:00:00,CUST0413,Corporate,Delhi,North,Home Appliances,Microwave,1.0,16007.70,Online,DTDC,16007.70,2026-03-16 00:00:00,NaN,Cancelled,NaN,Customer changed mind,NaN
2,ORD00003,2025-09-28 00:00:00,CUST0637,Consumer,Bengaluru,South,Furniture,Study Table,5.0,3752.98,Online,Delhivery,18764.90,2025-10-03 00:00:00,2025-10-05 00:00:00,Delivered,2.0,NaN,NaN
3,ORD00004,2025-04-17 00:00:00,CUST1103,Corporate,Ahmedabad,West,Fashion,Sneakers,4.0,2511.85,Mobile App,DTDC,10047.40,2025-04-22 00:00:00,2025-04-23 00:00:00,Delivered,1.0,NaN,NaN
4,ORD00005,2025-03-13 00:00:00,CUST1791,Small Business,Ahmedabad,West,Furniture,Dining Table,1.0,4852.38,Marketplace,Blue Dart,4852.38,2025-03-16 00:00:00,2025-03-21 00:00:00,Delivered,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7998,ORD07999,2026-05-04 00:00:00,CUST1327,Consumer,Hyderabad,South,Beauty,Perfume,3.0,2001.61,Marketplace,DTDC,6004.83,2026-05-07 00:00:00,2026-05-07 00:00:00,Returned,NaN,NaN,Damaged product
7999,ORD08000,2025-10-17 00:00:00,CUST0122,Consumer,Ahmedabad,West,Beauty,Moisturizer,5.0,1290.44,Online,Delhivery,6452.20,2025-10-21 00:00:00,2025-10-21 00:00:00,Delivered,0.0,NaN,NaN
8000,ORD00101,2025-02-10 00:00:00,CUST1288,Consumer,Bengaluru,South,Electronics,Smartphone,4.0,7507.51,Online,Delhivery,30030.04,2025-02-13 00:00:00,2025-02-13 00:00:00,Delivered,0.0,NaN,NaN
8001,ORD00501,2025-07-05 00:00:00,CUST1967,Small Business,Coimbatore,South,Grocery,Snacks,3.0,1207.18,Online,Delhivery,3621.54,2025-07-10 00:00:00,NaN,Cancelled,NaN,Customer changed mind,NaN
8002,ORD01501,2025-07-27 00:00:00,CUST0856,Corporate,Kochi,South,Electronics,Tablet,2.0,20112.61,Online,Ecom Express,40225.22,2025-07-31 00:00:00,2025-07-31 00:00:00,Delivered,0.0,NaN,NaN

In [2]:
df.shape

(8003, 19)

In [3]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Segment', 'City',
       'Region', 'Product_Category', 'Product', 'Quantity', 'Unit_Price',
       'Sales_Channel', 'Delivery_Partner', 'Order_Value',
       'Expected_Delivery_Date', 'Actual_Delivery_Date', 'Order_Status',
       'Delay_Days', 'Cancellation_Reason', 'Return_Reason'],
      dtype='str')

In [4]:
df.dtypes

Order_ID                      str
Order_Date                    str
Customer_ID                   str
Customer_Segment              str
City                          str
Region                        str
Product_Category              str
Product                       str
Quantity                  float64
Unit_Price                float64
Sales_Channel                 str
Delivery_Partner              str
Order_Value               float64
Expected_Delivery_Date        str
Actual_Delivery_Date          str
Order_Status                  str
Delay_Days                float64
Cancellation_Reason           str
Return_Reason                 str
dtype: object

In [5]:
df.isnull().sum()

Order_ID                     0
Order_Date                   0
Customer_ID                  0
Customer_Segment             1
City                         0
Region                       0
Product_Category             0
Product                      0
Quantity                     1
Unit_Price                   1
Sales_Channel                0
Delivery_Partner             0
Order_Value                  1
Expected_Delivery_Date       1
Actual_Delivery_Date       622
Order_Status                 0
Delay_Days                1092
Cancellation_Reason       7381
Return_Reason             7533
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(3)

In [7]:
df["Customer_ID"].unique()

<StringArray>
['CUST0196', 'CUST0413', 'CUST0637', 'CUST1103', 'CUST1791', 'CUST1681',
 'CUST1107', 'CUST0742', 'CUST0137', 'CUST0539',
 ...
 'CUST1290', 'CUST1218', 'CUST0759', 'CUST0325', 'CUST0567', 'CUST1900',
 'CUST0112', 'CUST0068', 'CUST1006', 'CUST1403']
Length: 1963, dtype: str

In [8]:
df["Order_Status"].value_counts()

Order_Status
Delivered    6911
Cancelled     622
Returned      470
Name: count, dtype: int64

In [9]:
df["Delivery_Partner"].value_counts()

Delivery_Partner
Delhivery       1917
Ecom Express    1627
Blue Dart       1561
DTDC            1479
XpressBees      1418
Delhivery          1
Name: count, dtype: int64

In [10]:
df["Product_Category"].value_counts()

Product_Category
Electronics        1838
Home Appliances    1428
Fashion            1417
Grocery            1209
Furniture          1138
Beauty              972
electronics           1
Name: count, dtype: int64

In [11]:
df.isnull().sum()

Order_ID                     0
Order_Date                   0
Customer_ID                  0
Customer_Segment             1
City                         0
Region                       0
Product_Category             0
Product                      0
Quantity                     1
Unit_Price                   1
Sales_Channel                0
Delivery_Partner             0
Order_Value                  1
Expected_Delivery_Date       1
Actual_Delivery_Date       622
Order_Status                 0
Delay_Days                1092
Cancellation_Reason       7381
Return_Reason             7533
dtype: int64

In [12]:
df["Quantity"].sum()

np.float64(24028.0)

In [13]:
df["Unit_Price"].mean()

np.float64(8178.064538865284)

In [14]:
df["Order_Value"].sum()

np.float64(195820615.72000003)

In [15]:
df["Order_Value"].mean()

np.float64(24471.459100224947)

In [16]:
df["Region"].value_counts()

Region
South    4002
West     2396
East      804
North     801
Name: count, dtype: int64

In [17]:
df["Customer_Segment"].value_counts()

Customer_Segment
Consumer          4584
Corporate         1812
Small Business    1606
Name: count, dtype: int64

In [18]:
df.groupby("Customer_Segment")["Order_Value"].mean()

Customer_Segment
Consumer          24644.232690
Corporate         24052.893838
Small Business    24461.363232
Name: Order_Value, dtype: float64

In [19]:
df.groupby("Product_Category")["Order_Value"].sum().sort_values(ascending=False)

Product_Category
Electronics        99239938.33
Home Appliances    51344560.54
Furniture          28375800.68
Fashion             9318412.05
Beauty              4175925.05
Grocery             3343930.51
electronics           22048.56
Name: Order_Value, dtype: float64

In [20]:
df.groupby("Delivery_Partner")["Order_Value"].sum().sort_values(ascending=False)

Delivery_Partner
Delhivery       48244320.01
Blue Dart       39137214.47
Ecom Express    37156048.38
DTDC            36003288.42
XpressBees      35271792.93
Delhivery           7951.51
Name: Order_Value, dtype: float64

In [21]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df["Expected_Delivery_Date"]=pd.to_datetime(df["Expected_Delivery_Date"])
df["Actual_Delivery_Date"]=pd.to_datetime(df["Actual_Delivery_Date"])
df

,Order_ID,Order_Date,Customer_ID,Customer_Segment,City,Region,Product_Category,Product,Quantity,Unit_Price,Sales_Channel,Delivery_Partner,Order_Value,Expected_Delivery_Date,Actual_Delivery_Date,Order_Status,Delay_Days,Cancellation_Reason,Return_Reason
0,ORD00001,2025-04-13,CUST0196,Corporate,Mumbai,West,Grocery,Coffee,4.0,824.14,Mobile App,Delhivery,3296.56,2025-04-18,2025-04-19,Returned,NaN,NaN,Damaged product
1,ORD00002,2026-03-12,CUST0413,Corporate,Delhi,North,Home Appliances,Microwave,1.0,16007.70,Online,DTDC,16007.70,2026-03-16,NaT,Cancelled,NaN,Customer changed mind,NaN
2,ORD00003,2025-09-28,CUST0637,Consumer,Bengaluru,South,Furniture,Study Table,5.0,3752.98,Online,Delhivery,18764.90,2025-10-03,2025-10-05,Delivered,2.0,NaN,NaN
3,ORD00004,2025-04-17,CUST1103,Corporate,Ahmedabad,West,Fashion,Sneakers,4.0,2511.85,Mobile App,DTDC,10047.40,2025-04-22,2025-04-23,Delivered,1.0,NaN,NaN
4,ORD00005,2025-03-13,CUST1791,Small Business,Ahmedabad,West,Furniture,Dining Table,1.0,4852.38,Marketplace,Blue Dart,4852.38,2025-03-16,2025-03-21,Delivered,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7998,ORD07999,2026-05-04,CUST1327,Consumer,Hyderabad,South,Beauty,Perfume,3.0,2001.61,Marketplace,DTDC,6004.83,2026-05-07,2026-05-07,Returned,NaN,NaN,Damaged product
7999,ORD08000,2025-10-17,CUST0122,Consumer,Ahmedabad,West,Beauty,Moisturizer,5.0,1290.44,Online,Delhivery,6452.20,2025-10-21,2025-10-21,Delivered,0.0,NaN,NaN
8000,ORD00101,2025-02-10,CUST1288,Consumer,Bengaluru,South,Electronics,Smartphone,4.0,7507.51,Online,Delhivery,30030.04,2025-02-13,2025-02-13,Delivered,0.0,NaN,NaN
8001,ORD00501,2025-07-05,CUST1967,Small Business,Coimbatore,South,Grocery,Snacks,3.0,1207.18,Online,Delhivery,3621.54,2025-07-10,NaT,Cancelled,NaN,Customer changed mind,NaN
8002,ORD01501,2025-07-27,CUST0856,Corporate,Kochi,South,Electronics,Tablet,2.0,20112.61,Online,Ecom Express,40225.22,2025-07-31,2025-07-31,Delivered,0.0,NaN,NaN

In [22]:
df.groupby("Product")["Order_Value"].sum().sort_values(ascending=False).head(5)

Product
Headphones    20564762.07
Tablet        20358322.00
Laptop        19902097.34
Smartphone    19393891.78
Smartwatch    19042913.70
Name: Order_Value, dtype: float64

In [23]:
df.groupby("Region")["Order_Value"].mean().sort_values(ascending=False)

Region
North    25016.872447
East     24874.861121
South    24476.359153
West     24145.742104
Name: Order_Value, dtype: float64

In [24]:
df.groupby("Sales_Channel")["Order_Value"].sum().sort_values(ascending=False)

Sales_Channel
Online         89179868.39
Marketplace    58172507.17
Mobile App     48468240.16
Name: Order_Value, dtype: float64

In [25]:
df.loc[df["Delay_Days"]>0,
"Delivery_Partner"].value_counts()

Delivery_Partner
Delhivery       958
Ecom Express    794
Blue Dart       783
DTDC            747
XpressBees      729
Name: count, dtype: int64

In [26]:
df.groupby("Product_Category")["Delay_Days"].sum().sort_values(ascending=False)

Product_Category
Electronics        2452.0
Home Appliances    2089.0
Fashion            1883.0
Grocery            1765.0
Furniture          1610.0
Beauty             1363.0
electronics           4.0
Name: Delay_Days, dtype: float64

In [27]:
df[df["Order_Status"]=="Cancelled"]["City"].value_counts().head(5)

City
Kochi        72
Bengaluru    70
Delhi        69
Mumbai       69
Kolkata      65
Name: count, dtype: int64

In [28]:
df["Cancellation_Reason"].value_counts()

Cancellation_Reason
Address issue            138
Customer changed mind    132
Payment issue            122
Partner capacity         117
Inventory unavailable    113
Name: count, dtype: int64

In [29]:
(df[df["Order_Status"] == "Returned"]
 .groupby("Product_Category")
 .size()
 / df.groupby("Product_Category").size() * 100
).sort_values(ascending=False)

Product_Category
Home Appliances    6.302521
Beauty             6.172840
Electronics        6.039173
Grocery            5.872622
Fashion            5.575159
Furniture          5.184534
electronics             NaN
dtype: float64

In [30]:
df.groupby("City")["Delay_Days"].mean().sort_values(ascending=False).head(5)

City
Bangalore     4.000000
Kolkata       1.714080
Coimbatore    1.701149
Mumbai        1.669540
Pune          1.636496
Name: Delay_Days, dtype: float64